name: smart_home_flutter
description: Smart Home App with Dynamic UI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  amplify_flutter: ^1.0.0
  amplify_auth_cognito: ^1.0.0
  amplify_api: ^1.0.0
  intl: ^0.18.0
  logger: ^1.1.0
  mqtt_client: ^9.8.1
  mockito: ^5.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/images/