// This file is generated by Flutter's build system and should not be edited manually.

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

// ignore: public_member_api_docs
void registerPlugins(Registrar registrar) {
  // No need to register plugins for web specifically as they will be registered
  // through the generated plugin registrant
  registerPlugins(registrar);
}